name: Build wheels

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | bash -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          rustup target add x86_64-unknown-linux-musl

      - name: Build wheels for 3.10, 3.11, 3.12, 3.13, 3.14
        run: |
          for pybin in /opt/python/cp{310,311,312,313,314}-cp*/bin/python; do
            $pybin -m pip install --upgrade pip setuptools wheel tomli
            $pybin -m pip install "maturin[patchelf]"
            $pybin -m maturin build --release --target x86_64-unknown-linux-musl --out dist --no-sdist
          done

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.whl
